Add working Version from Metting Yesterday
LukasW352435/INFM_HIL_Interface pull request #16
Opened 2021-11-17 14:28 UTC by genesfa

2021-11-17 16:59 UTC, Bl4d3s requested changes

2021-11-17 16:59 UTC, Bl4d3s commented on Sim_To_DuT_Interface/Sim_Communication/SimComHandler.cpp
> +        simEventMap["Opperation"] = simEvent.operation;
Typo

2021-11-17 16:59 UTC, Bl4d3s commented on Sim_To_DuT_Interface/Sim_Communication/SimComHandler.cpp
> +                keyVektor.push_back(element.first);
vector with c. ist bei ein paar vars ^^

2021-11-17 16:59 UTC, Bl4d3s commented on Sim_To_DuT_Interface/Sim_Communication/SimComHandler.cpp
>          // zmq::context_t context_sub(1);
Auskommentierte Zeilen noch nötig? Sonst bitte entfernen

2021-11-17 16:59 UTC, Bl4d3s commented on Sim_To_DuT_Interface/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} libs zmq quill boost_serialization stdc++fs)
stdc++fs mit if:
if (CMAKE_CXX_COMPILER_VERSION GREATER_EQUAL 9)
    target_link_libraries(${PROJECT_NAME} libs zmq quill boost_serialization) 
else()
    target_link_libraries(${PROJECT_NAME} libs zmq quill boost_serialization stdc++fs) 
endif()

2021-11-18 15:08 UTC, genesfa commented on Sim_To_DuT_Interface/Sim_Communication/SimComHandler.cpp
> +        simEventMap["Opperation"] = simEvent.operation;
Wurde gefixed ŝtand aber bei euch auch irgendwo des wegen haben wir es übernommen ^^

2021-11-19 18:02 UTC, Bl4d3s approved these changes

2021-11-19 18:02 UTC, merged