Logger events
LukasW352435/INFM_HIL_Interface pull request #21
Opened 2021-11-22 20:29 UTC by mak5338

* Logger kann nun Events loggen (Bei Änderung am Event-Objekt können Probleme auftreten)
* Es kann nun wahlweise ein absoluter Pfad für die logfiles angegeben werden, statt nur ein relativer
* Auslagerung konfigurierbarer Attribute in eine Config.h
* Verbesserung der Doc

2021-11-22 20:44 UTC, Bl4d3s requested changes

2021-11-22 20:44 UTC, Bl4d3s commented on Sim_To_DuT_Interface/DuTLogger/DuTLogger.cpp
> +        LOG_INFO(dataLogger, "{},{},{},{}", event.operation, castedValue, event.origin, event.current);
Können nur Strings geloggt werden? Es würde doch im CSV mehr Sinn machen den Datentyp zu erhalten?

2021-11-22 20:44 UTC, Bl4d3s commented on Sim_To_DuT_Interface/DuTLogger/DuTLogger.cpp
> +        switch (event.value.which()) {
Wenn die Reihenfolge geändert werden würde geht das nicht mehr. 

Fände es analog zu dem besser:
boost::variant<int, bool, std::string> container;
container = "Hello world";

if (container.type() == typeid(std::string)) {
    std::cout << "Found a string: " << boost::get<std::string>(container);
}
else if (container.type() == typeid(int)) {
    std::cout << "Found an int: " << boost::get<int>(container);
}

2021-11-22 21:21 UTC, mak5338 commented on Sim_To_DuT_Interface/DuTLogger/DuTLogger.cpp
> +        switch (event.value.which()) {
Ja das stimmt. Deswegen habe ich den try-catch gemacht. Im Falle, dass die Reihenfolge geändert wird, würde er einfach aufhören Events zu loggen und stattdessen Fehlermeldungen loggen. 
Aber ich find deins besser :D kannte die Methode nicht, werds aber morgen ausbessern

2021-11-22 21:25 UTC, mak5338 commented on Sim_To_DuT_Interface/DuTLogger/DuTLogger.cpp
> +        LOG_INFO(dataLogger, "{},{},{},{}", event.operation, castedValue, event.origin, event.current);
Die Formatierung war nur nötig, weil quill das boost::variant nicht mochte und eher primitive typen wie int, char, string haben möchte. Der Datentyp wird jedoch erhalten. Also ein Beispiel für ein Event wär:
Operation,Value,Origin,Current
Start,23,Sim,1637609761

Ich werd mal ein Beispiel-File auf Discord posten

2021-11-23 18:08 UTC, mak5338 commented
Änderungen aus Besprechung heute (23.11.2021) übernommen

2021-11-25 18:14 UTC, mab0189 approved these changes
Changes reviewed and approved.

2021-11-25 18:36 UTC, Bl4d3s approved these changes

2021-11-25 18:39 UTC, merged