Used boost::visitor pattern for different type value
LukasW352435/INFM_HIL_Interface pull request #24
Opened 2021-11-26 13:38 UTC by mak5338

Christinas Verbesserungsvorschlag eines visitor-Patterns für event.value eingebaut

2021-11-26 14:39 UTC, LukasW352435 approved these changes
Habe ich getestet, funktioniert so wie erwartet.
Jedoch gibt es ein Problem wenn ich folgendes mache:
DuTLogger::logEvent(sim_interface::SimEvent("Test,,,,LOL",1,"Test2");
Dann stimmt halt die CSV Datei nicht mehr. Ist meiner Meinung nach jedoch akzeptabel.

2021-11-26 14:49 UTC, mak5338 commented
@LukasW352435 Das stimmt. Wenn in dem Namen der Operation ein Komma ist, dann wird das auch so ins CSV geschrieben. Dann ist das CSV nicht mehr richtig. Soll ich noch eine Funktion einfügen, die alle Kommas in den Parametern durch andere Zeichen ersetzt?

2021-11-26 14:59 UTC, Bl4d3s commented
> 

Man kann im CSV auch escapen. das würde ich machen. Siehe: [StackOverflow](https://stackoverflow.com/questions/4617935/is-there-a-way-to-include-commas-in-csv-columns-without-breaking-the-formatting)

2021-11-26 14:59 UTC, mak5338 commented
Oder ich verwende diese Methode: https://stackoverflow.com/questions/4617935/is-there-a-way-to-include-commas-in-csv-columns-without-breaking-the-formatting

2021-11-26 15:00 UTC, mak5338 commented
Ah gleichzeitig

2021-11-26 16:24 UTC, Bl4d3s commented
Andere Sache: warum eigtl DuTLogger, wäre InterfaceLogger nicht sinnvoller?

2021-11-26 17:39 UTC, mak5338 commented
Naja bisher hatte niemand was gegen den Namen. Wenn der neue Name besser ist, können es schon ändern, aber dann brauch ich Hilfe, weil ich nicht weiß, wie ich das Git Submodule umkonfiguriere. Und die aktuellen Pull-Requests müssen halt nochmal überarbeitet werden.

2021-11-26 18:03 UTC, mab0189 commented
> Andere Sache: warum eigtl DuTLogger, wäre InterfaceLogger nicht sinnvoller?

Der Name würde schon mehr Sinn machen aber meiner Meinung nach würde ich das in einem neuen Pull Request behandeln.

2021-11-26 20:58 UTC, mak5338 commented
Stimmt, den Namen kann ich ja dann in einem neuen PR ändern, wenn jeder seine Logging Nachrichten reingeschmissen hat. Dann ist auch das Refactor einfacher, denk ich.

@LukasW352435 ich hab noch was dazu implementiert, damit dein Spezialfall ebenfalls nach den CSV-Regeln von Wikipedia richig behandelt und gelogged wird.

2021-11-27 11:53 UTC, LukasW352435 commented
> Stimmt, den Namen kann ich ja dann in einem neuen PR ändern, wenn jeder seine Logging Nachrichten reingeschmissen hat. Dann ist auch das Refactor einfacher, denk ich.
> 
> @LukasW352435 ich hab noch was dazu implementiert, damit dein Spezialfall ebenfalls nach den CSV-Regeln von Wikipedia richig behandelt und gelogged wird.

Perfekt, ich teste das am Montag

2021-11-27 13:06 UTC, Bl4d3s requested changes
Sobald ich die Funktion DuTLogger::logEvent(simEvent) aufrufe, bekomme ich immer #include "quill/Quill.h" no such file or directory. Irgendwas scheint da mit dem Build nicht zu stimmen

2021-11-27 16:02 UTC, Bl4d3s approved these changes

2021-11-27 16:02 UTC, merged